CREATE TABLE IF NOT EXISTS ORDEMINVESTIMENTO (
    idOrdem BIGINT PRIMARY KEY,
    idConta BIGINT NOT NULL,
    idInvest BIGINT NOT NULL,
    quantiaInvest FLOAT NOT NULL,
    dataInvest TIMESTAMP NOT NULL,
    FOREIGN KEY (idConta) REFERENCES CONTAINVESTIMENT(idConta),
    FOREIGN KEY (idInvest) REFERENCES INVESTIMENT(idInvest)
)